services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - web/.env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    restart: on-failure:5
    networks:
      - app_network

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - server/.env
    environment:
      - PORT=3001
    restart: on-failure:5
    networks:
      - app_network

  crew-agent:
    build:
      context: ./crew-agent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - crew-agent/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure:5
    networks:
      - app_network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # REST API port
      - "6334:6334" # GRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - app_network
    restart: on-failure:5

networks:
  app_network:
    driver: bridge
